// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $.tips({
      action: 'focus',
      element: '.error',
      tooltipClass: 'error'
    });
    $.tips({
      action: 'click',
      element: '.clicktips',
      tooltipClass: 'warning',
      preventDefault: true
    });
    return $.tips({
      action: 'hover',
      element: '.hover',
      preventDefault: true,
      html5: false
    });
  });

}).call(this);
